#!/usr/bin/env bash
# shellcheck disable=SC2086
#
# health-check.sh — Periodic Health Check (G23)
#
# Verifies the entire toolkit is healthy. Runs targeted checks against scripts,
# contract files, rules, git branch safety, dependencies, and gitnexus index.
#
# Usage:
#   ./scripts/health-check.sh                           # All checks (default)
#   ./scripts/health-check.sh --check scripts           # Scripts only
#   ./scripts/health-check.sh --check contract           # Contract files only
#   ./scripts/health-check.sh --check rules              # Rules only
#   ./scripts/health-check.sh --check git                # Git branch safety
#   ./scripts/health-check.sh --check deps               # Dependencies only
#   ./scripts/health-check.sh --check index              # GitNexus index only
#   ./scripts/health-check.sh --fix                      # Auto-fix minor issues
#   ./scripts/health-check.sh --verbose                  # Detailed output
#   ./scripts/health-check.sh --output json              # Machine-readable JSON
#   ./scripts/health-check.sh --help                     # Show this message
#
# Exit codes:
#   0 — All healthy
#   1 — Warnings (non-critical issues)
#   2 — Critical failures
#
# Requirements:
#   - bash 4+
#   - git (for branch detection)
#   - jq (for JSON validation and parsing)
#   - bc, python3 (optional, used by contract checks)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Config ──────────────────────────────────────────────────────────────────
VERBOSE=false
DO_FIX=false
OUTPUT_MODE="plain"   # plain or json
CHECK_MODE="all"      # all, scripts, contract, rules, git, deps, index
EXIT_CODE=0
HAS_WARNINGS=false
HAS_CRITICAL=false

# ── Known scripts list — generated by scanning scripts/ ─────────────────────
CHECK_SCRIPTS=()
while IFS= read -r -d '' script; do
    CHECK_SCRIPTS+=("$(basename "$script")")
done < <(find "$SCRIPT_DIR" -maxdepth 1 -name '*.sh' -print0 2>/dev/null || true)

# ── Critical files to verify existence ──────────────────────────────────────
CRITICAL_FILES=(
    "contract/contract.template.json"
    "contract/contract.schema.json"
    "rules/rules.json"
    "agent.md"
    "README.md"
)

# ── Colors ──────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    CYAN='\033[0;36m'
    BOLD='\033[1m'
    NC='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; CYAN=''; BOLD=''; NC=''
fi

# ── Help ────────────────────────────────────────────────────────────────────
usage() {
    cat <<'USAGE'
health-check.sh — Periodic Health Check (G23)

SYNOPSIS
    ./scripts/health-check.sh [OPTIONS]

OPTIONS
    --help              Show this help message and exit
    --check TYPE        Run specific check type: scripts|contract|rules|git|deps|index
    --check-all         Run all checks (default)
    --fix               Auto-fix minor issues (re-index gitnexus if stale, re-create missing dirs)
    --verbose           Show details per check
    --output FORMAT     Output format: plain (default) or json

CHECK TYPES
    scripts     Verify all scripts in scripts/ exist and are executable
    contract    Verify contract files exist and are valid JSON
    rules       Verify rules.json is valid and has required keys
    git         Verify git branch is not main/master
    deps        Check required dependencies (jq, git, bc, python3)
    index       Check gitnexus index freshness

FIX ACTIONS
    --fix enables auto-repair for:
    - Re-index gitnexus if stale (>1 hour old or after code changes)
    - Re-create missing session/ directories
    - Set executable bit on scripts

EXIT CODES
    0   All healthy
    1   Warnings (non-critical issues)
    2   Critical failures

OUTPUT
    Results are written to session/{branch}/health.json for audit trail

EXAMPLES
    ./scripts/health-check.sh
    ./scripts/health-check.sh --check deps
    ./scripts/health-check.sh --check all --fix --verbose
    ./scripts/health-check.sh --output json
USAGE
    exit 0
}

# ── Logging ─────────────────────────────────────────────────────────────────
log_pass() { local msg="$1"; if [[ "$OUTPUT_MODE" == "json" ]]; then echo "[PASS] $msg" >&2; else echo -e "  ${GREEN}[PASS]${NC} $msg"; fi; }
log_fail() { local msg="$1"; HAS_CRITICAL=true; if [[ "$OUTPUT_MODE" == "json" ]]; then echo "[FAIL] $msg" >&2; else echo -e "  ${RED}[FAIL]${NC} $msg"; fi; }
log_warn() { local msg="$1"; HAS_WARNINGS=true; if [[ "$OUTPUT_MODE" == "json" ]]; then echo "[WARN] $msg" >&2; else echo -e "  ${YELLOW}[WARN]${NC} $msg"; fi; }
log_info() { local msg="$1"; if [[ "$VERBOSE" == true ]]; then if [[ "$OUTPUT_MODE" == "json" ]]; then echo "[INFO] $msg" >&2; else echo -e "  ${CYAN}[INFO]${NC} $msg"; fi; fi; }
log_verbose() { local msg="$1"; if [[ "$VERBOSE" == true ]]; then if [[ "$OUTPUT_MODE" == "json" ]]; then echo "  :: $msg" >&2; else echo "  :: $msg"; fi; fi; }
log_dry() { local msg="$1"; if [[ "$OUTPUT_MODE" == "json" ]]; then echo "[DRY-RUN] $msg" >&2; else echo -e "  ${CYAN}[DRY-RUN]${NC} $msg"; fi; }
log_section() { local msg="$1"; if [[ "$OUTPUT_MODE" == "json" ]]; then echo "== $msg" >&2; else echo -e "\n${BOLD}==${NC} ${BOLD}$msg${NC}"; fi; }

# ── Helpers ─────────────────────────────────────────────────────────────────
get_branch() { git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "unknown"; }
get_timestamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
is_executable() { [[ -x "$1" ]] && return 0 || return 1; }

check_dep() {
    local name="$1" binary="$2" optional="${3:-false}"
    if command -v "$binary" &>/dev/null; then log_pass "Dependency '$name' ($binary) found"; return 0
    else
        if [[ "$optional" == "true" ]]; then log_warn "Dependency '$name' ($binary) not found (optional)"; return 0
        else log_fail "Dependency '$name' ($binary) not found"; return 1; fi
    fi
}

# ── Check: Scripts ──────────────────────────────────────────────────────────
check_scripts() {
    local total=0 missing=0 not_exec=0
    log_section "Check: Scripts"
    if [[ ${#CHECK_SCRIPTS[@]} -eq 0 ]]; then log_fail "No scripts found in scripts/"; return 1; fi
    for script in "${CHECK_SCRIPTS[@]}"; do
        total=$((total + 1))
        local fp="$SCRIPT_DIR/$script"
        if [[ ! -f "$fp" ]]; then log_fail "Script missing: $script"; missing=$((missing + 1)); continue; fi
        if ! is_executable "$fp"; then log_warn "Script not executable: $script"; not_exec=$((not_exec + 1)); fi
        log_verbose "Found: $script ($(wc -l < "$fp") lines)"
    done
    log_info "Scripts: $total total, $missing missing, $not_exec not executable"
    if [[ "$missing" -gt 0 ]]; then log_fail "Missing scripts detected"; return 1; fi
    if [[ "$not_exec" -gt 0 ]]; then log_warn "${not_exec} script(s) not executable — use --fix to correct"; return 0; fi
    log_pass "All $total scripts present and executable"; return 0
}

# ── Check: Contract ─────────────────────────────────────────────────────────
check_contract() {
    local all_pass=true
    log_section "Check: Contract"
    for rel_path in "${CRITICAL_FILES[@]}"; do
        local fp="$PROJECT_DIR/$rel_path"
        if [[ ! -f "$fp" ]]; then log_fail "Missing critical file: $rel_path"; all_pass=false; continue; fi
        log_verbose "Found: $rel_path"
        if [[ "$rel_path" == *.json ]]; then
            if python3 -c "import json,sys; json.load(open('$fp')); sys.exit(0)" 2>/dev/null; then log_verbose "  JSON valid: $rel_path"
            else log_fail "Invalid JSON: $rel_path"; all_pass=false; fi
        fi
    done
    if [[ "$all_pass" == true ]]; then log_pass "All critical files present and valid"; return 0
    else log_fail "Critical file issues detected"; return 1; fi
}

# ── Check: Rules ────────────────────────────────────────────────────────────
check_rules() {
    log_section "Check: Rules"
    local rules_file="$PROJECT_DIR/rules/rules.json"
    if [[ ! -f "$rules_file" ]]; then log_fail "rules.json not found"; return 1; fi
    python3 -c "import json; json.load(open('$rules_file'))" 2>/dev/null || { log_fail "rules.json is not valid JSON"; return 1; }
    if command -v jq &>/dev/null; then
        for k in state_machine scoring ponytail agent_watchdog; do
            jq -e ".$k" "$rules_file" &>/dev/null || { log_fail "rules.json missing key: $k"; return 1; }
        done
        for k in states transitions; do
            jq -e ".state_machine.$k" "$rules_file" &>/dev/null || { log_fail "rules.json missing state_machine.$k"; return 1; }
        done
        log_info "Transitions: $(jq '.state_machine.transitions | length' "$rules_file")"
        log_info "Pass threshold: $(jq -r '.scoring.thresholds.pass' "$rules_file")"
    fi
    log_pass "rules.json valid with all required keys"; return 0
}

# ── Check: Git ──────────────────────────────────────────────────────────────
check_git() {
    log_section "Check: Git"
    local branch; branch="$(get_branch)"
    if [[ -z "$branch" || "$branch" == "unknown" ]]; then log_fail "Could not detect git branch"; return 1; fi
    log_info "Current branch: $branch"
    if [[ "$branch" == "main" || "$branch" == "master" ]]; then log_fail "On protected branch '$branch'"; return 1; fi
    git -C "$PROJECT_DIR" rev-parse --git-dir &>/dev/null || { log_fail "Not in a git repository"; return 1; }
    log_pass "Git branch '$branch' is safe"; return 0
}

# ── Check: Dependencies ─────────────────────────────────────────────────────
check_deps() {
    log_section "Check: Dependencies"
    local ok=true
    check_dep "git" "git" "false" || ok=false
    check_dep "jq" "jq" "false" || ok=false
    check_dep "bc" "bc" "true" || true
    check_dep "python3" "python3" "true" || true
    if [[ "$ok" == true ]]; then log_pass "All required dependencies available"; fi
    return 0
}

# ── Check: GitNexus Index ──────────────────────────────────────────────────
check_index() {
    log_section "Check: GitNexus Index"
    local gd="$PROJECT_DIR/.gitnexus"
    if [[ ! -d "$gd" ]]; then log_fail "GitNexus index not found (.gitnexus/ missing)"; return 1; fi
    local idx=""
    if [[ -f "$gd/analysis.json" ]]; then idx="$gd/analysis.json"
    elif [[ -f "$gd/index.json" ]]; then idx="$gd/index.json"
    elif [[ -d "$gd/data" ]]; then idx=$(find "$gd/data" -name '*.json' -print0 | xargs -0 ls -t 2>/dev/null | head -1); fi
    if [[ -z "$idx" || ! -f "$idx" ]]; then log_fail "GitNexus index files not found"; return 1; fi
    local it; it=$(stat -f "%m" "$idx" 2>/dev/null || stat -c "%Y" "$idx" 2>/dev/null || echo 0)
    local age=$(( $(date +%s) - it )); local ah=$((age / 3600))
    log_info "GitNexus index age: ${ah}h ($((age / 60))m)"
    if [[ "$age" -gt 3600 ]]; then
        log_warn "GitNexus index is ${ah}h old — consider re-indexing"
        if [[ "$DO_FIX" == true ]]; then
            log_info "Auto-fix: re-indexing..."
            if bash "$SCRIPT_DIR/gitnexus-analyze.sh" 2>/dev/null; then log_pass "GitNexus index refreshed"
            else log_fail "Failed to re-index GitNexus"; return 1; fi
        fi
    else log_pass "GitNexus index is fresh (${ah}h old)"; fi
    local uc; uc=$(git -C "$PROJECT_DIR" status --porcelain 2>/dev/null | wc -l | tr -d ' ')
    [[ "$uc" -gt 0 ]] && log_warn "${uc} uncommitted change(s) — index may be stale"
    return 0
}

# ── Fix Mode ────────────────────────────────────────────────────────────────
do_fix() {
    log_section "Auto-Fix Mode"; local fixes=0
    for s in "${CHECK_SCRIPTS[@]}"; do
        local fp="$SCRIPT_DIR/$s"
        if [[ -f "$fp" ]] && ! is_executable "$fp"; then chmod +x "$fp" 2>/dev/null && log_info "Made executable: $s" && fixes=$((fixes + 1)); fi
    done
    local br; br="$(get_branch)"; local sd="$PROJECT_DIR/session/$br"
    if [[ ! -d "$sd" ]]; then mkdir -p "$sd"; log_info "Created: $sd"; fixes=$((fixes + 1)); fi
    if [[ ! -f "$PROJECT_DIR/session/index.md" ]]; then
        { echo "# Session Index — Workflow State Engine"; echo ""; echo "| Branch | Active | Status | Last State | Score | PR | Last Activity |"; echo "|--------|--------|--------|------------|-------|----|--------------|"; } > "$PROJECT_DIR/session/index.md"
        fixes=$((fixes + 1))
    fi
    if [[ ! -f "$PROJECT_DIR/session/state.md" ]]; then
        { echo "# Session State History — Workflow State Engine"; echo ""; echo "| Date | Branch | State | Score | PR/Commit | Summary |"; echo "|------|--------|-------|-------|-----------|---------|"; } > "$PROJECT_DIR/session/state.md"
        fixes=$((fixes + 1))
    fi
    if [[ "$fixes" -gt 0 ]]; then log_pass "Applied $fixes fix(es)"; else log_pass "Nothing to fix"; fi
}

# ── Persist to session/{branch}/health.json ────────────────────────────────
persist_results() {
    local branch="$1" report="$2"
    local sd="$PROJECT_DIR/session/$branch"; mkdir -p "$sd"
    local ts; ts="$(get_timestamp)"
    echo "{\"timestamp\":\"$ts\",\"branch\":\"$branch\",\"check_mode\":\"$CHECK_MODE\",\"results\":$report,\"exit_code\":$EXIT_CODE,\"has_warnings\":$HAS_WARNINGS,\"has_critical\":$HAS_CRITICAL}" > "$sd/health.json"
    log_verbose "Persisted to: $sd/health.json"
}

# ── Final Report ────────────────────────────────────────────────────────────
render_report() {
    local rj="$1"
    if [[ "$OUTPUT_MODE" == "json" ]]; then echo "$rj"; return; fi
    echo -e "\n${BOLD}Health Check — Workflow State Engine${NC}\n"
    if [[ "$HAS_CRITICAL" == true ]]; then echo -e "  ${RED}[FAIL]${NC} Critical failures\n  ${BOLD}Exit:${NC} 2 (CRITICAL)"; EXIT_CODE=2
    elif [[ "$HAS_WARNINGS" == true ]]; then echo -e "  ${YELLOW}[WARN]${NC} Warnings\n  ${BOLD}Exit:${NC} 1 (WARNINGS)"; EXIT_CODE=1
    else echo -e "  ${GREEN}[PASS]${NC} All checks passed\n  ${BOLD}Exit:${NC} 0 (HEALTHY)"; EXIT_CODE=0; fi
}

main() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --help) usage ;;
            --check-all) CHECK_MODE="all"; shift ;;
            --check)
                if [[ -z "${2:-}" ]]; then echo "Error: --check requires argument"; exit 1; fi
                CHECK_MODE="$2"; shift 2 ;;
            --fix) DO_FIX=true; shift ;;
            --verbose) VERBOSE=true; shift ;;
            --output)
                if [[ -z "${2:-}" ]]; then echo "Error: --output requires argument"; exit 1; fi
                [[ "$2" != "plain" && "$2" != "json" ]] && { echo "Error: --output must be plain/json"; exit 1; }
                OUTPUT_MODE="$2"; shift 2 ;;
            *) echo "Unknown: $1"; echo "Use --help."; exit 1 ;;
        esac
    done
    local br; br="$(get_branch)"
    log_section "Health Check — $br"
    log_verbose "Mode: $CHECK_MODE, Fix: $DO_FIX, Output: $OUTPUT_MODE"
    case "$CHECK_MODE" in
        all|*) check_scripts || true; check_contract || true; check_rules || true; check_git || true; check_deps || true; check_index || true ;;
        scripts) check_scripts || true ;;
        contract) check_contract || true ;;
        rules) check_rules || true ;;
        git) check_git || true ;;
        deps) check_deps || true ;;
        index) check_index || true ;;
    esac
    if [[ "$DO_FIX" == true ]]; then do_fix; fi
    local rj
    rj=$(jq -n --arg m "$CHECK_MODE" --argjson w "$HAS_WARNINGS" --argjson c "$HAS_CRITICAL" --arg b "$br" '{check_mode:$m,branch:$b,has_warnings:$w,has_critical:$c}' 2>/dev/null || echo "{\"check_mode\":\"$CHECK_MODE\",\"branch\":\"$br\",\"has_warnings\":$HAS_WARNINGS,\"has_critical\":$HAS_CRITICAL}")
    persist_results "$br" "$rj"
    render_report "$rj"
    exit "$EXIT_CODE"
}

main "$@"